kafka:
  pool: nav-dev
cluster: dev-gcp
ingress:
  url: https://tiltakspenger-soknad-api.dev.nav.no
endpoints:
  pdl: https://pdl-api.dev-fss-pub.nais.io/graphql
  pdf: https://tiltakspenger-pdfgen.intern.dev.nav.no
  joark: https://dokarkiv.dev-fss-pub.nais.io
audience:
  pdl: dev-fss:pdl:pdl-api
  joark: dev-fss:teamdokumenthandtering:dokarkiv
scope:
  pdl: api://dev-fss.pdl.pdl-api/.default
  joark: api://dev-fss.teamdokumenthandtering.dokarkiv/.default
