kafka:
  pool: nav-dev
cluster: dev-gcp
outboundExternalUrls:
  pdl: pdl-api.dev-fss-pub.nais.io
  dokarkiv: dokarkiv-q2.dev-fss-pub.nais.io
sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: false
  tier: db-f1-micro
