kafka:
  pool: nav-dev
cluster: dev-gcp
endpoints:
  pdl: https://pdl-api.dev-fss-pub.nais.io/graphql
  pdf: http://tiltakspenger-pdfgen
  dokarkiv: https://dokarkiv-q2.dev-fss-pub.nais.io
  tiltakspengertiltak: http://tiltakspenger-tiltak
  tiltakspengervedtak: http://tiltakspenger-saksbehandling-api
  av: http://clamav.nais-system/scan
outboundExternalUrls:
  pdl: pdl-api.dev-fss-pub.nais.io
  dokarkiv: dokarkiv-q2.dev-fss-pub.nais.io
scope:
  pdl: dev-fss:pdl:pdl-api
  dokarkiv: dev-fss:teamdokumenthandtering:dokarkiv
  vedtak: dev-gcp:tpts:tiltakspenger-saksbehandling-api
  tiltakspengertiltak: dev-gcp:tpts:tiltakspenger-tiltak
sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: false
  tier: db-f1-micro
