kafka:
  pool: nav-dev
cluster: dev-gcp
ingresses: |
  ingresses:
    - https://tiltakspenger-soknad-api.intern.dev.nav.no
endpoints:
  pdl: https://pdl-api.dev-fss-pub.nais.io/graphql
  pdf: http://tiltakspenger-pdfgen
  dokument: http://tiltakspenger-dokument
  tiltakspengerarena: https://tiltakspenger-arena.dev-fss-pub.nais.io
  av: http://clamav.nais-system/scan
outboundExternalUrls:
  pdl: pdl-api.dev-fss-pub.nais.io
  tiltakspengerarena: tiltakspenger-arena.dev-fss-pub.nais.io
audience:
  pdl: dev-fss:pdl:pdl-api
  tiltakspengerarena: dev-fss:tpts:tiltakspenger-arena
scope:
  pdl: api://dev-fss.pdl.pdl-api/.default
unleash:
  environment: development
