kafka:
  pool: nav-prod
cluster: prod-gcp
endpoints:
  pdl: https://pdl-api.prod-fss-pub.nais.io/graphql
  pdf: http://tiltakspenger-pdfgen
  dokarkiv: https://dokarkiv.prod-fss-pub.nais.io
  tiltakspengertiltak: http://tiltakspenger-tiltak
  tiltakspengervedtak: http://tiltakspenger-saksbehandling-api
  av: http://clamav.nais-system/scan
outboundExternalUrls:
  pdl: pdl-api.prod-fss-pub.nais.io
  dokarkiv: dokarkiv.prod-fss-pub.nais.io
scope:
  pdl: prod-fss:pdl:pdl-api
  dokarkiv: prod-fss:teamdokumenthandtering:dokarkiv
  vedtak: prod-gcp:tpts:tiltakspenger-saksbehandling-api
  tiltakspengertiltak: prod-gcp:tpts:tiltakspenger-tiltak
sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: true
  tier: db-custom-1-3840