kafka:
  pool: nav-prod
cluster: prod-gcp
outboundExternalUrls:
  pdl: pdl-api.prod-fss-pub.nais.io
  dokarkiv: dokarkiv.prod-fss-pub.nais.io
sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: true
  tier: db-custom-1-3840