kafka:
  pool: nav-prod
cluster: prod-gcp
endpoints:
  pdl: https://pdl-api.prod-fss-pub.nais.io/graphql
  dokument: http://tiltakspenger-dokument
  tiltakspengerarena: https://tiltakspenger-arena.prod-fss-pub.nais.io
  av: http://clamav.nais-system/scan
outboundExternalUrls:
  pdl: pdl-api.prod-fss-pub.nais.io
  tiltakspengerarena: tiltakspenger-arena.prod-fss-pub.nais.io
audience:
  pdl: prod-fss:pdl:pdl-api
  tiltakspengerarena: prod-fss:tpts:tiltakspenger-arena
scope:
  pdl: api://prod-fss.pdl.pdl-api/.default
unleash:
  environment: production
