apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-soknad-api
  namespace: tpts
  labels:
    team: tpts
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  ingresses:
    - {{ ingress.url }}
  prometheus:
    enabled: false
    path: /metrics
  replicas:
    min: 2
    max: 2
  kafka:
    pool: {{ kafka.pool }}
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-soknad
          namespace: tpts
          cluster: {{ cluster }}
    outbound:
      rules:
        - application: tiltakspenger-pdfgen
        - application: clamav
          namespace: clamav
      external:
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "dokarkiv.dev-fss-pub.nais.io"
        - host: "tiltakspenger-arena.dev-fss-pub.nais.io"
  env:
    - name: PDL_ENDPOINT_URL
      value: {{ endpoints.pdl }}
    - name: PDL_AUDIENCE
      value: {{ audience.pdl }}
    - name: PDL_SCOPE
      value: {{ scope.pdl }}
    - name: JOARK_ENDPOINT_URL
      value: {{ endpoints.joark }}
    - name: JOARK_AUDIENCE
      value: {{ audience.joark }}
    - name: JOARK_SCOPE
      value: {{ scope.joark }}
    - name: PDF_ENDPOINT_URL
      value: {{ endpoints.pdf }}
    - name: AV_ENDPOINT_URL
      value: {{ endpoints.av }}
    - name: TILTAKSPENGER_ARENA_ENDPOINT_URL
      value: {{ endpoints.tiltakspengerarena }}
    - name: TILTAKSPENGER_ARENA_AUDIENCE
      value: {{ audience.tiltakspengerarena }}
