apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: tiltakspenger-soknad-api
  namespace: tpts
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: tiltakspenger
  secretName: tiltakspenger-soknad-api-unleash-api-token
  environment: {{ unleash.environment }}
