version: "3.7"

services:
  auth:
    image: "ghcr.io/navikt/mock-oauth2-server:0.5.1"
    container_name: auth
    ports:
      - "6969:6969"
    environment:
      SERVER_PORT: 6969
      JSON_CONFIG: >
        {
            "interactiveLogin": true,
            "httpServer": "NettyWrapper",
            "tokenCallbacks": [
                {
                    "issuerId": "idporten",
                    "tokenExpiry": 3600,
                    "requestMappings": [
                        {
                            "requestParam": "grant_type",
                            "match": "*",
                            "claims": {
                                "sub": "12345678901",
                                "pid": "12345678901"
                            }
                        }
                    ]
                }
            ]
        }
