name: Deploy alerts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".nais/alerts.yml"

jobs:
  deploy:
    name: Deploy alerts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to NAIS (dev)
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts.yml
      - name: Deploy to NAIS (prod)
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yml
