name: Deploy alerts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".nais/alerts.yml"

jobs:
  deploy:
    name: Deploy alerts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # Deploysteget leser kun manifestfiler - tokenet trengs ikke videre.
          persist-credentials: false
      - name: Deploy to NAIS (dev)
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts.yml
      - name: Deploy to NAIS (prod)
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yml
