name: Post slack notification on pull request

on:
  pull_request:
    branches:
      - main

jobs:
  notify:
    name: Notify tiltakspenger-pull-requests
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Post message
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_ON_PUSH_WEBHOOK_URL }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          curl -X POST --data "{\"text\": \"Ny pull request: $GITHUB_ACTOR på $GITHUB_REPOSITORY - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA - ${{ env.COMMIT_MESSAGE }}\"}" $WEBHOOK_URL