name: Post slack notification on pull request

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  notify:
    name: Notify tiltakspenger-pull-requests
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Post message
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_ON_PUSH_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.url }}
        run: |
          curl -X POST --data "{\"text\": \"Pull request åpnet: $GITHUB_ACTOR på $GITHUB_REPOSITORY - $PR_URL - PR_TITLE\"}" $WEBHOOK_URL